### ISSUE TITLE
Deploying to GitHub Pages not working

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-community/rust-meetup-template#7]
Hey, we're trying to use this template for the next all hands, however when trying to deploy this [on travis](https://travis-ci.org/XAMPPRocky/all-hands-2020/jobs/589654490#L385) it tries to run rake and errors out. I don't have experience with ruby so I'm not really sure how to fix this. 
```
Traceback (most recent call last):
387	4: from /home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `<main>'
388	3: from /home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `eval'
389	2: from /home/travis/.rvm/gems/ruby-2.5.3@global/bin/rake:23:in `<main>'
390	1: from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
391/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```

**Comment by skade** [comment]
Jekyll for GH pages is not setup for deployment via travis. It's best to do this via the normal GitHub pages interface (activate pages in the settings, have GH pick it up and build).

**Comment by XAMPPRocky** [comment]
Ah I see, I just assumed CI was required. Thanks!
